// boilerplate, We can replace our hand-written rootReducer with a shorter one generated by combineReducers.
import { combineReducers } from 'redux'


import todos from './features/todos/todoReducer'
import filters from './features/filters/filterReducer'

const rootReducer = combineReducers({
  // Define a top-level state field named `todos`, handled by `todosReducer`
  todos: todos, // the key names will become the keys in your root state object
  filters: filters
})

export default rootReducer